server:
  proxy:
    hostport: 0.0.0.0:5432
  admin:
    hostport: 0.0.0.0:10000

nodes:
  master:
    hostport: 192.168.56.100:5432
    role: master
    metadata: {}
  replica:
    hostport: 192.168.56.101:5432
    role: replica
    metadata: {}

credentials:
  username: postgres
  password: password
  database: postgres
  ssl:
    enable: false
    sslmode: disable
  options:
    application_name: crunchy-proxy

pool:
  capacity: 2

healthcheck:
  delay: 60
  query: select now()

