---

- name: "Configure postgresql.conf"
  lineinfile:
    dest: "{{ postgresql_config_file }}"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_config_options }}"

# Configure pg_hba.conf
- name: "Configure pg_hba.conf"
  lineinfile:
    dest: "{{ postgresql_hba_file }}"
    regexp: "^#?{{ item.type }}.+S"
    line: "{{ item.type}}\t{{ item.database }}\t{{ item.user }}\t{{ item.address}}\t{{ item.method }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_hba_entries }}"

