---

- hosts: all

  tasks:
  # Include common tasks.
  - include: "tasks/common-tasks.yml"

  # Include common PG variables and tasks.
  - include_vars: "vars/pg-common-vars.yml"
  - include: "tasks/pg-common-tasks.yml"

  # Include replica specific configuration variables.
  #- include_vars: "vars/replica-vars.yml"

  # Setup replica.
  # TODO

  # Configure.
  #  - include: "tasks/pg-configure-tasks.yml"
  
  # Install SSL Certificates
  #- include: "tasks/pg-ssl-tasks.yml"
